FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch
ENV INITSYSTEM on
RUN echo "deb http://ftp.debian.org/debian stretch-backports main" >> /etc/apt/sources.list

RUN apt-get update && apt-get install -y iptables 
RUN apt-get -t stretch-backports install -yq \
	network-manager && \
	apt-get clean && rm -rf /var/lib/apt/lists/* && \
	systemctl mask NetworkManager.service

WORKDIR /usr/src/app
COPY . .
ENV UDEV=1
CMD ./start