#! /bin/bash
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
nmcli connection modify balena-hotspot1 802-11-wireless.ssid $WIFI_NAME
nmcli connection modify balena-hotspot1 802-11-wireless-security.psk $WIFI_PW
nmcli connection modify balena-wifi 802-11-wireless.ssid $WIFI_CON_NAME
nmcli connection modify balena-wifi 802-11-wireless-security.psk $WIFI_CON_PW
nmcli connection down balena-hotspot1
nmcli connection down balena-wifi
nmcli connection up balena-hotspot1
nmcli connection up balena-wifi
sleep 2
ip="null"
oldip="null"
while true; do
    ip=`ifconfig eth0| sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'| cut -d'.' -f1-3`
    #echo "Update - IP is: $ip"
    if [[ "$oldip" != "$ip" ]]; then
        oldip=$ip
        if [[ $ip == *"."*"."* ]]; then
            echo "IP Set to $ip"
            ip2="$ip.$ROUTER_IP"
            ip="$ip.0/24"
            iptables -D FORWARD -o eth0 -j DROP  2>/dev/null || true
            iptables -D FORWARD -i wlan0 -o eth0 -d $ip -j DROP  2>/dev/null || true
            iptables -I FORWARD -i wlan0 -o eth0 -d $ip -j DROP  2>/dev/null || true
            echo "Second IP $ip2"
            nmcli connection modify my-ethernet1 ipv4.addresses $ip2
            nmcli connection down my-ethernet1 && nmcli connection up my-ethernet1
        else
            echo "No IP Set"
            iptables -I FORWARD -o eth0 -j DROP  2>/dev/null || true
        fi
    fi
    sleep 10
done
