FROM balenalib/%%BALENA_MACHINE_NAME%%-debian
ENV INITSYSTEM on

#RUN apt-get update && apt-get install -y wget cron bzip2

RUN apt-get update && apt-get install -yq --no-install-recommends \
	cron wget bzip2 \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

#RUN mkdir backup
RUN mkdir sync

RUN wget -O /usr/src/app/gdrive https://drive.google.com/uc?id=1f5Q-yAwUYZYt_frYjodFHbU0v7ppQkem&export=download && wait
RUN chmod +x /usr/src/app/gdrive
RUN mv gdrive /bin/

COPY ./start .
COPY ./backup.sh .
COPY ./token_v2.json /root/.gdrive/
RUN sed -i -e 's/\r$//' backup.sh

ENV UDEV=1

RUN chmod +x /usr/src/app/backup.sh
RUN echo "30 1 * * * /usr/src/app/backup.sh" | crontab


CMD ./start