#! /bin/bash

sleep 5
echo "Start"
echo "$RESIN_DEVICE_UUID" > "config"
echo "$FILE_LIMIT" >> "config"
echo "$BALENA_APP_NAME" >> "config"
echo "$BALENA_DEVICE_NAME_AT_INIT" >> "config"
echo "$GDRIVE_FOLDER_ID" >> "config"
sleep 5
service cron restart

while true; do
    sleep 60
done