FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:stretch-run
ENV INITSYSTEM on

RUN apt-get update && apt-get install -y build-essential git wget python jq

RUN wget https://nodejs.org/dist/v4.6.2/node-v4.6.2-linux-armv6l.tar.gz -P /tmp
RUN cd /usr/local && tar xzvf /tmp/node-v4.6.2-linux-armv6l.tar.gz --strip=1


WORKDIR /usr/src/app

RUN mkdir pimatic-app
RUN mkdir userdata
#Copy UserData
COPY ./config ./userdata/

RUN npm install pimatic --prefix pimatic-app --production

COPY ./start .

ENV UDEV=1

#RUN npm install --unsafe-perm sqlite3 --prefix pimatic-app 

CMD ./start