FROM balenalib/%%BALENA_MACHINE_NAME%%-node:10.16
ENV INITSYSTEM on

RUN apt-get update && apt-get install -y build-essential git wget python jq netcat \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN mkdir pimatic-app
RUN mkdir userdata
#Copy UserData
COPY ./config ./userdata/

RUN npm install -g node-gyp
RUN npm install -g node-pre-gyp

RUN npm install pimatic --prefix pimatic-app --production

COPY ./start .

ENV UDEV=1

RUN npm install --unsafe-perm sqlite3 --prefix pimatic-app 

RUN npm install --unsafe-perm pimatic-cron --prefix pimatic-app 
RUN npm install --unsafe-perm pimatic-mobile-frontend --prefix pimatic-app 
RUN npm install --unsafe-perm pimatic-shell-execute --prefix pimatic-app 
#RUN npm install --unsafe-perm pimatic-echo --prefix pimatic-app
RUN npm install michbeck100/pimatic-echo#master --prefix pimatic-app
RUN npm install --unsafe-perm pimatic-mysensors --prefix pimatic-app 
RUN npm install dfischbach/pimatic-coc#master --prefix pimatic-app 

CMD ./start